### ISSUE TITLE
 Interesting and meaningful work!! 

### ISSUE THREAD

**Issue by ucas-hao** [hamidkazemi22/CLIPInversion#1]
Interesting and meaningful work!!  I find it very interesting, but I am wondering if this can be extended to other modalities, such as audios or videos?

**Comment by hamidkazemi22** [comment]
Thank you for your keen interest in our endeavors! Expanding our scope to include other modalities, such as audio, is a fantastic idea. For instance, leveraging the CLAP model, a contrastive model designed for both audio and text could prove highly beneficial. However, we must determine the most effective regularization techniques tailored for audio. Currently, we're using Total Variation and other regularization methods, some of which are primarily suited for images.
